services:
  backend:
    build: 
      context: ./django
    # command: command
    ports:
      - 8000:8000
    networks:
      - django-react

  frontend:
    build: 
      context: ./react/blogapi
    volumes:
      - react_build:/react/build
    networks:
      - django-react

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
      - ./django/staticfiles:/var/www/django/staticfiles:ro
      - ./django/media:/var/www/django/media:ro
    depends_on:
      - backend
      - frontend
    networks:
      - django-react

volumes:
  react_build:

networks:
  django-react:
    driver: bridge
